package goStr

var apaMinorWords = map[string]bool{
	"a":     true,
	"an":    true,
	"the":   true,
	"and":   true,
	"but":   true,
	"or":    true,
	"for":   true,
	"nor":   true,
	"on":    true,
	"at":    true,
	"to":    true,
	"by":    true,
	"with":  true,
	"of":    true,
	"in":    true,
	"into":  true,
	"near":  true,
	"over":  true,
	"off":   true,
	"up":    true,
	"down":  true,
	"out":   true,
	"as":    true,
	"about": true,
	"from":  true,
	"via":   true,
}
